setup/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('el_tukio.urls'))
]

el_tukio/models.py
from django.db import models
from django.db.models.deletion import CASCADE, SET_NULL
from django.contrib.auth.models import AbstractUser
from django.urls import reverse
from django.db.models import CheckConstraint, Q, F
from django.utils.translation import gettext_lazy as _
from django.core.validators import MaxValueValidator, MinValueValidator
from django.core.exceptions import ValidationError
from django.db.models.signals import m2m_changed

from phonenumber_field.modelfields import PhoneNumberField
from PIL import Image
import os


class Location(models.Model):
    route = models.CharField(help_text='Road/Street name', max_length=255)
    neighbourhood = models.CharField(help_text='Neighbourhood/Estate', max_length=255, blank=True, null=True)
    city = models.CharField(max_length=255)
    county = models.CharField(help_text='State/Province/County', max_length=255)
    postal_code = models.CharField(max_length=255, blank=True, null=True)
    country = models.CharField(max_length=255)
    longitude = models.FloatField(blank=True, null=True)
    latitude = models.FloatField(blank=True, null=True)
    maps_url = models.CharField(max_length=1024, blank=True, null=True)

    def __string__(self):
        return f'{self.route}, {self.city}, {self.country}'


class User(AbstractUser):
    """Model representing a general system user"""
    class UserType(models.IntegerChoices):
        ORGANIZER = 0, _('Organizer')
        PLANNER = 1, _('Planner')
        VENDOR = 3, _('Vendor')

        __empty__ = _('(Unkown)')

    class AccountType(models.IntegerChoices):
        PERSONAL = 1, _('Personal')
        ORGANIZATION = 2, _('Organization')
        
        __empty__ = _('--------------')

    user_type = models.SmallIntegerField(blank=True, null=True, choices=UserType.choices)
    phone_number = PhoneNumberField(blank=True, null=True, unique=True)
    profile = models.ImageField(default='default.png', upload_to='profile_pics')
    account_type = models.SmallIntegerField(blank=True, null=True, choices=UserType.choices)
    location = models.OneToOneField(Location, blank=True, null=True, on_delete=models.SET_NULL)

    @property
    def is_organizer(self):
        return self.user_type == self.UserType.ORGANIZER

    @property
    def is_planner(self):
        return self.user_type == self.UserType.PLANNER
    
    @property
    def is_vendor(self):
        return self.user_type == self.UserType.VENDOR

    @property
    def user_role(self):
        if self.is_organizer or self.is_planner:
            return self.get_user_type_display()
        elif self.is_vendor:
            return self.vendor.category.name

    @property
    def full_name(self):
        return self.get_full_name()

    def get_absolute_url(self):
        """Return the url to access a particular user"""
        return reverse('user-details', args=[str(self.id)])

    class Meta:
        ordering = ['last_name', 'first_name']

    def __str__(self):
        return self.full_name

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)

        # resize big images using 'Pillow'
        # 'django-cleanup' deletes old version of the image once it is changed!
        img = Image.open(self.profile.path)
        if img.height > 300 or img.width > 300:
            img_size = (300, 300)
            img.thumbnail(img_size)
            img.save(self.profile.path)


class Comment(models.Model):
    user = models.ForeignKey(User, on_delete=CASCADE)
    comment = models.CharField(max_length=500)
    date_posted = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"{self.user.full_name}'s comment"


class FileUpload(models.Model):
    user = models.ForeignKey(User, on_delete=CASCADE)
    file = models.FileField(upload_to='uploads/')
    date_uploaded = models.DateTimeField(auto_now_add=True)

    @property
    def filename(self):
        return os.path.basename(self.file.name)

    def __str__(self):
        return self.filename


class LegalDocument(FileUpload):
    class DocumentType(models.IntegerChoices):
        BUSINESS_PERMIT = 1, _('Business permit or license')

    title = models.SmallIntegerField(choices=DocumentType.choices)

    @property
    def title_display(self):
        return self.get_title_display()

    def __string__(self):
        return self.filename


class BusinessProfile(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    business_name = models.CharField(max_length=255)
    docs = models.ManyToManyField(LegalDocument)


class ChatRoom(models.Model):
    class Type(models.IntegerChoices):
        PERSONAL = 0, _('Personal')
        GROUP = 1, _('Group')

    name = models.CharField(max_length=50, blank=True, null=True)
    type = models.SmallIntegerField(choices=Type.choices)
    members = models.ManyToManyField(User, blank=True, related_name='chatroom')


# limit members in personal chat
def chat_members_changed(sender, **kwargs):
    chatroom = kwargs['instance']
    if chatroom.type == ChatRoom.Type.PERSONAL and chatroom.members.count() > 2:
        raise ValidationError(_("Personal chat can't have more than 2 people!"))

m2m_changed.connect(chat_members_changed, sender=ChatRoom.members.through)


class ChatMessage(models.Model):
    chatroom = models.ForeignKey(ChatRoom, on_delete=CASCADE)
    message = models.CharField(max_length=5000, help_text='Enter message...')
    sender = models.ForeignKey(User, on_delete=CASCADE)
    date_sent = models.DateTimeField(auto_now_add=True)
    reply_to = models.BigIntegerField(blank=True, null=True)

    @property
    def reference(self):
        return ChatMessage.objects.get(id=self.reply_to)

    class Meta:
        ordering = ['date_sent']


class VendorCategory(models.Model):
    """Model representing a wedding vendor category. 
    Vendor categories are added by the Admin in the database. """
    name = models.CharField( max_length=200, help_text='Select a category (EG: Venues)')

    class Meta:
        verbose_name = _('Vendor Category')
        verbose_name_plural = _('Vendor Categories')

    def __str__(self):
        return self.name


class Organizer(models.Model):
    """Model representing a system user who's an organizer of an event"""
    user = models.OneToOneField(User, on_delete=CASCADE, primary_key=True)
    bookmarks = models.ManyToManyField(User, related_name='organizer_bookmarks')

    def __str__(self):
        return f'{self.user} (organizer)'


class Planner(models.Model):
    """Model representing a system user who's a professional planner of events"""
    user = models.OneToOneField(User, on_delete=CASCADE, primary_key=True)
    description = models.TextField(max_length=5000, help_text='Brief description of your business')
    services_offered = models.TextField(max_length=5000, help_text='List the particular services your business offers')
    city = models.CharField(max_length=100, help_text='Primary (Current) city of residence')
    location = models.CharField(max_length=200, help_text='EG: Ole Sangale Rd, Madaraka')  # street code
    up_for_business = models.BooleanField(default=True, help_text='Ready to take business at the moment?')
    bookmarks = models.ManyToManyField(User, related_name='planner_bookmarks')

    def __str__(self):
        return f'{self.user} (planner)'


class Vendor(models.Model):
    """Model representing a system user who's a vendor"""
    user = models.OneToOneField(User, on_delete=CASCADE, primary_key=True)
    business_name = models.CharField(max_length=100)
    category = models.ForeignKey(VendorCategory, on_delete=SET_NULL, null=True, blank=True, help_text='Select a category for your business.')
    description = models.TextField(max_length=5000, help_text='Brief description of your business')
    services_offered = models.TextField(max_length=5000, help_text='List the particular services your business offers')
    city = models.CharField(max_length=100, help_text='City in which your business is located')
    location = models.CharField(max_length=200, help_text='EG: Ole Sangale Rd, Madaraka')  # street code
    open_hours = models.CharField(max_length=500, default='24/7', help_text='Business service (working) times')
    up_for_business = models.BooleanField(default=True, help_text='Ready to take business at the moment?')

    def get_absolute_url(self):
        """Return the url to access a particular vendor"""
        return reverse('vendor-details', args=[str(self.id)])

    def __str__(self):
        return f'{self.business_name} ({self.category})'


class VendorImageUpload(models.Model):
    """Model representing a vendor's image upload"""
    vendor = models.ForeignKey(Vendor, on_delete=models.CASCADE)
    image = models.ImageField(upload_to='vendor_img_uploads')
    caption = models.CharField(max_length=500, null=True, blank=True)

    def __str__(self):
        return f"{self.vendor.business_name}'s image"


class Event(models.Model):
    """Model representing an event"""
    organizer = models.ForeignKey(Organizer, on_delete=CASCADE)
    event_name = models.CharField(max_length=100)
    event_date = models.DateField(help_text='When will this event be held?')
    event_budget = models.FloatField(help_text='What  is the budget for this event?')
    event_location = models.CharField(max_length=100, null=True, blank=True)
    guest_size = models.IntegerField(help_text='Expected number of guests at the event?')
    event_team = models.ManyToManyField(User, related_name='event_team_members')
    chatroom = models.OneToOneField(ChatRoom, on_delete=SET_NULL, blank=True, null=True)

    def __str__(self):
        return self.event_name
    

class Review(models.Model):
    """Model representing an event organizer's rating of a planner or vendor"""
    organizer = models.ForeignKey(Organizer, on_delete=CASCADE)
    rated_user = models.ForeignKey(User, on_delete=CASCADE, related_name='rated_planner_or_vendor', editable=False)

el_tukio/views/planner.py
from django.shortcuts import render, redirect
from django.views.generic import CreateView
from django.contrib.auth import login
from django.contrib import messages
from django.utils.decorators import method_decorator

from el_tukio.forms import PlannerRegForm
from el_tukio.models import User
from el_tukio.utils.decorators import planner_required


# @method_decorator(planner_required, name='dispatch')
class Register(CreateView):
    # model = User
    form_class = PlannerRegForm
    template_name = 'main/register/planner.html'
    extra_context = {'title': 'Event planner Registration'}

    def form_valid(self, form):
        user = form.save()
        login(self.request, user)
        messages.success(self.request, 'Login successful!')
        return redirect('planner-dashboard')


@planner_required
def dashboard(request):
    return render(request, 'planner/dashboard.html')

el_tukio/views/vendor.py
from django.shortcuts import render, redirect
from django.views.generic import CreateView
from django.contrib.auth import login
from django.contrib import messages
from django.utils.decorators import method_decorator
from django.views.generic import UpdateView
from django.shortcuts import get_object_or_404

from el_tukio.forms import VendorRegForm, BusinessProfileForm, VendorImageUploadForm
from el_tukio.models import User, Vendor, VendorImageUpload
from el_tukio.utils.decorators import vendor_required
from el_tukio.utils.main import print_form_values


class Register(CreateView):
    model = User
    form_class = VendorRegForm
    template_name = 'main/register/vendor.html'
    extra_context = {'title': 'Vendor Registration'}

    def form_valid(self, form):
        user = form.save()
        login(self.request, user)
        messages.success(self.request, 'Login successful!')
        return redirect('vendor-dashboard')


@vendor_required
def dashboard(request):
    return render(request, 'vendor/dashboard.html')


@vendor_required
def profile(request):
    return render(request, 'vendor/profile.html')


@method_decorator(vendor_required, name='dispatch')
class BusinessProfileUpdate(UpdateView):
    form_class = BusinessProfileForm
    template_name = 'vendor/profile-update.html'

    def get_object(self):
        return get_object_or_404(Vendor, pk=self.request.user.pk)

    def form_valid(self, form):
        form.save()
        messages.success(self.request, 'Business profile updated!')
        return redirect('vendor-profile')


@vendor_required
def business_gallery(request):
    context = {
        'gallery': VendorImageUpload.objects.filter(vendor_id=request.user.pk),
        'form': VendorImageUploadForm
    }
    return render(request, 'vendor/business-gallery.html', context)


@vendor_required
def upload_business_image(request):
    form = VendorImageUploadForm(request.POST, request.FILES)
    if not form.is_valid():
        messages.error(request, form.errors.as_text())
        return redirect('business-gallery')

    image = form.cleaned_data['image']
    caption = form.cleaned_data['caption']
    img = VendorImageUpload(
        vendor_id = request.user.id,
        image=image,
        caption=caption,
    )
    img.save()
    messages.success(request, 'New image uploaded!')
    return redirect('business-gallery')

templates/main/bookmarks.html
{% extends 'base.html' %}

{% block title %} Bookmarks {% endblock %}

{% block body %}
{% include 'components/header.html' %}

<div class="p-body">
    <div class="results-wrapper text-center">
        <div class="row row-cols-1 row-cols-md-3 row-cols-lg-4 justify-content-center">
            {% for seller in bookmarks %}
            <div class="col">
                <div class="card card-search-result p-1 rounded-sm shadow h-100">
                    <img src="{{ seller.user.profile.url }}" class="rounded" alt="profile">
                    <div class="card-body">
                        <div class="fs-6"><strong>
                            {% if seller.user.is_vendor %}
                            {{ seller.business_name }}
                            {% else %}
                            {{ seller.user.full_name }}
                            {% endif %}
                        </strong></div>
                        <div class="rating">
                            <span class="text-warning"><i class="fas fa-star"></i></span>
                            <span class="num">4.5 - 5 reviews</span>
                        </div>
                        <div class="card-subtitle text-muted">{{ seller.location }} - {{ seller.city }}</div>
                        <small class="btn-secondary rounded px-2">
                            {% if seller.user.is_vendor %}
                            {{ seller.category.name }}
                            {% else %}
                            {{ seller.user.get_user_type_display }}
                            {% endif %}
                        </small>
                        <div class="d-flex justify-content-center gap-lg mt-3">
                            <a href="{% url 'remove-bookmark' seller.user_id %}" class="text-success">
                                <i class="fa-solid fa-heart"></i>
                                Saved
                            </a>
                            <a href="{% url 'seller-details' seller.user_id %}">
                                View more
                                <i class="fa-solid fa-chevron-right"></i>
                            </a>
                        </div>
                    </div>
                </div>
            </div>
            {% empty %}
            <div class="text-danger">No vendor bookmarked!</div>
            {% endfor %}
        </div>
    </div>
</div>

{% endblock body %}

templates/main/calendar.html
{% extends 'layouts/dashboard.html' %}
{% load static %}
{% load widget_tweaks %}

{% block content %}

<h5 class="mt-4 mb-5">My custom calendar</h5>

<div class="row row-cols-2">
    {% comment %} *** Due items *** {% endcomment %}
    <div class="col">
        <div class="todays text-start">
            <h3 class="text-uppercase mb-4">{{ active_dt|date:"l" }} <br>{{ active_dt|date:"F jS" }}</h3>
            <ul class="list-group">
                {% comment %} Tasks {% endcomment %}
                <h6 class="text-danger text-decoration-underline mb-0">Tasks due today</h6>
                {% for task in due_tasks %}
                <li class="list-group-item border-0 px-0">
                    <div>{{ task.task }}</div>
                    <span class="text-primary" title="Due date">
                        <i class="fa-regular fa-calendar"></i>
                        {{ task.due_date }}
                    </span>
                    {% if task.task_group %}
                    <a role="button" href="{% url 'organizer-event-tasks' task.event.id task.task_group_id %}" class="btn btn-sm btn-info px-1 py-0">{{ task.task_group }}</a>
                    {% else %}
                    <a role="button" href="{% url 'organizer-event-tasks' task.event.id %}" class="btn btn-sm btn-info px-1 py-0">Tasks</a>
                    {% endif %}
                    <a role="button" href="{% url 'organizer-event-details' task.event.id %}" class="btn btn-sm btn-secondary px-1 py-0">
                        {{ task.event }}
                    </a>
                </li>
                {% empty %}
                <div class="text-success mt-2">No tasks due!</div>
                {% endfor %}

                {% comment %} Bills/expenses {% endcomment %}
                <h6 class="text-danger text-decoration-underline mb-0 mt-4">Bills not settled yet</h6>
                {% for xp in due_bills %}
                <li class="list-group-item border-0 px-0">
                    <div>
                        {{ xp.description }}
                        <span>Cost: <strong>{{ xp.total_cost }}</strong></span>
                        <span>Paid: <strong>{{ xp.total_paid }}</strong></span>
                    </div>
                    <span class="text-primary" title="Date recorded">
                        <i class="fa-solid fa-pen"></i>
                        {{ xp.date_budgeted|date }}
                    </span>
                    <a role="button" href="{% url 'organizer-event-expenses' xp.event_id %}" class="btn btn-sm btn-info px-1 py-0">
                        {% if xp.expense_category %}
                        {{ xp.expense_category }}
                        {% else %}
                        General expenses
                        {% endif %}
                    </a>
                    <a role="button" href="{% url 'organizer-event-details' xp.event_id %}" class="btn btn-sm btn-secondary px-1 py-0">{{ xp.event }}</a>
                    {% empty %}
                    <div class="text-success mt-2">All events' bills settled!</div>
                    {% endfor %}
                </li>

                {% comment %} Chats {% endcomment %}
                <h6 class="text-danger text-decoration-underline mb-0 mt-4">New chats</h6>
                {% comment %} Guests without confirmation {% endcomment %}
                <h6 class="text-danger text-decoration-underline mb-0 mt-4">Guests not confirmed</h6>
            </ul>
        </div>
    </div>

    {% comment %} *** Calendar *** {% endcomment %}

    <div class="col">
        <div class="calendar rounded-md overflow-hidden border border-info">
            <div class="calendar-header bg-primary text-white rounded-top">
                <div class="calendar-header-highlight d-flex align-items-center justify-content-between py-4 px-3">
                    <a class="prev-month text-white" href="{% url 'calendar' yy=prev_year mm=prev_month %}">
                        <i class="fa-solid fa-chevron-left"></i>
                    </a>
                    <div class="month-info fw-bold text-uppercase">
                        {{ active_dt|date:"F" }} {{ active_dt.year }}
                    </div>
                    <a class="next-month text-white" href="{% url 'calendar' yy=next_year mm=next_month %}">
                        <i class="fa-solid fa-chevron-right"></i>
                    </a>
                </div>

                <div class="calendar-header-months d-flex align-items-center justify-content-between text-uppercase py-2 px-3" style="background: #1467e1">
                    <a role="button" class="{% if active_dt.month == 1 %}active{% endif %}" href="{% url 'calendar' yy=active_dt.year mm=1 %}">Jan</a>
                    <a role="button" class="{% if active_dt.month == 2 %}active{% endif %}" href="{% url 'calendar' yy=active_dt.year mm=2 %}">Feb</a>
                    <a role="button" class="{% if active_dt.month == 3 %}active{% endif %}" href="{% url 'calendar' yy=active_dt.year mm=3 %}">Mar</a>
                    <a role="button" class="{% if active_dt.month == 4 %}active{% endif %}" href="{% url 'calendar' yy=active_dt.year mm=4 %}">Apr</a>
                    <a role="button" class="{% if active_dt.month == 5 %}active{% endif %}" href="{% url 'calendar' yy=active_dt.year mm=5 %}">May</a>
                    <a role="button" class="{% if active_dt.month == 6 %}active{% endif %}" href="{% url 'calendar' yy=active_dt.year mm=6 %}">Jun</a>
                    <a role="button" class="{% if active_dt.month == 7 %}active{% endif %}" href="{% url 'calendar' yy=active_dt.year mm=7 %}">Jul</a>
                    <a role="button" class="{% if active_dt.month == 8 %}active{% endif %}" href="{% url 'calendar' yy=active_dt.year mm=8 %}">Aug</a>
                    <a role="button" class="{% if active_dt.month == 9 %}active{% endif %}" href="{% url 'calendar' yy=active_dt.year mm=9 %}">Sep</a>
                    <a role="button"class="{% if active_dt.month == 10 %}active{% endif %}" href="{% url 'calendar' yy=active_dt.year mm=10 %}">Oct</a>
                    <a role="button"class="{% if active_dt.month == 11 %}active{% endif %}" href="{% url 'calendar' yy=active_dt.year mm=11 %}">Nov</a>
                    <a role="button"class="{% if active_dt.month == 12 %}active{% endif %}" href="{% url 'calendar' yy=active_dt.year mm=12 %}">Dec</a>
                </div>
            </div>

            <div class="calendar-labels d-flex flex-items-equal align-items-center text-muted py-3">
                <div>Mon</div>
                <div>Tue</div>
                <div>Wed</div>
                <div>Thu</div>
                <div>Fri</div>
                <div>Sat</div>
                <div>Sun</div>
            </div>

            <div class="calendar-body">
                {% for e in num_skip %}
                <div class="blank"></div>
                {% endfor %}
                {% for dd in month_days %}
                <div class="date {% if active_dt.day == dd %}active{% endif %}">
                    <a role="button" href="{% url 'calendar' yy=active_dt.year mm=active_dt.month dd=dd %}">{{ dd }}</a>
                </div>
                {% endfor %}
            </div>
            <div class="calendar-footer rounded-bottom px-3 py-2">
                <a href="{% url 'calendar' %}" class="btn btn-sm btn-light text-primary fw-bold py-1">Today</a>
            </div>
        </div>
    </div>
</div>

{% endblock content %}

templates/main/chat.html
{% extends 'layouts/dashboard.html' %}
{% load static %}
{% load widget_tweaks %}

{% block content %}
{% include 'components/nav-event.html' %}

{% comment %} <h1 class="text-center">{{ event_chatroom.name }}</h1> {% endcomment %}
<div class="chat-inner d-flex flex-column">
    <div class="row row-cols-2">
        <div class="col-4">
            <div class="d-flex flex-column gap-sm">
                <strong class="text-muted mt-4">Chatting with:</strong>
                <a role="button" class="btn btn-{% if active_chat == 0 %}success{% else %}light{% endif %}" href="{% url 'event-chatroom' event.id %}" title="Chat with Everyone">
                    Everyone
                </a>
                {% for member in event_chatroom.members.all %}
                {% if member.id != user.id %}
                <a role="button" href="{% url 'event-chatroom' event_id=event.id chat_with=member.id %}" class="btn btn-{% if active_chat == member.id %}success{% else %}light{% endif %}" title="Chat with {{ member }}">
                    {{ member }}
                    <span class="text-muted">[{{ member.user_role }}]</span>
                </a>
                {% endif %}
                {% endfor %}
            </div>
        </div>

        <div class="col-8">
            <div class="card messages-wrapper tk-scrollbar">
                <div class="messages-inner d-flex flex-column gap-sm p-4">
                    {% for msg in active_chatroom.chatmessage_set.all %}
                    <div class="chat-message {% if msg.sender.id == user.id %}outgoing{% else %}incoming{% endif %} position-relative">
                        <div class="options position-absolute top-0 bottom-0 d-flex align-items-center gap-xsm px-2">
                            <a role="button" class="d-inline-flex align-items-center justify-content-center rounded-circle" onclick="replyTo({{ msg.id }}, this)" title="Reply">
                                <i class="fa-solid fa-reply"></i>
                            </a>
                            <a role="button" class="d-inline-flex align-items-center justify-content-center rounded-circle" onclick="" title="Delete">
                                <i class="fa-solid fa-trash-can"></i>
                            </a>
                        </div>
                        {% comment %} Original message if current is a reply {% endcomment %}
                        {% if msg.reference %}
                        <div class="chat-message-inner">
                            <p class="mb-0">
                                {% if msg.reference.sender.id != user.id %}
                                <span class="text-primary">{{ msg.reference.sender }}</span>
                                {% else %}
                                <span class="text-info">ME</span>
                                {% endif %}
                                <small class="text-muted">{{ msg.reference.date_sent }}</small>
                            </p>
                            <p class="mb-0">{{ msg.reference.message }}</p>
                        </div>
                        {% endif %}
                        {% comment %} Current message {% endcomment %}
                        <div class="chat-message-content">
                            <p class="mb-0">
                                {% if msg.sender.id != user.id %}
                                <span class="text-primary">{{ msg.sender }}</span>
                                {% else %}
                                <span class="text-info">ME</span>
                                {% endif %}
                                <small class="text-muted">{{ msg.date_sent }}</small>
                            </p>
                            <p class="mb-0">{{ msg.message }}</p>
                        </div>
                    </div>
                    {% empty %}
                    No messages yet!
                    {% endfor %}
                </div>
            </div>
        </div>
    </div>
</div>

<div class="chat-form-wrapper position-absolute start-0 end-0 bottom-0 bg-white p-2 border-top" id="chatFormWrapper">
    <form name="chatMessageForm" action="{{ request.path_info }}" method="POST" class="d-flex gap-sm">
        {% csrf_token %}
        <input type="hidden" name="chatroom" value="{{ active_chatroom.id }}">
        <input type="hidden" name="reference">
        {% render_field message_form.message class+='form-control' autofocus=True placeholder='Enter message...' %}
        <button type="submit" class="btn btn-primary">Send</button>
    </form>
</div>

{% endblock content %}

{% block scripts %}
<script src="{% static 'js/dom/chat.js' %}" defer></script>
{% endblock scripts %}

templates/main/hire-seller.html
{% extends 'base.html' %}
{% load widget_tweaks %}

{% block title %} Hire {{ seller.user.full_name }} {{ seller.business_name }} {% endblock %}

{% block body %}

<div class="p-body">
    <div class="mt-5 mb-4 text-center">
        <h4>Hire {{ seller.user.full_name }} {{ seller.business_name }}</h4>
        <small class="d-inline-block btn-secondary rounded px-2 mb-2">{{ seller.user.user_role }}</small>
        {% for x in events %}
        {% if seller.user in x.event_team.all %}
        <div class="text-success">Already part of '{{ x.event_name }}' event team!</div>
        {% endif %}
        {% for c in x.contract_set.all %}
        {% if c.is_pending and seller.user_id == c.contractee_id %}
        <div class="text-success">Contract already sent for '{{ x.event_name }}' event!</div>
        {% endif %}
        {% endfor %}
        {% endfor %}
    </div>

    <form action="{{ request.path_info }}" method="POST">
        {% csrf_token %}

        <div class="form-field mb-3">
            <label for="id_event">Event:</label>
            <select name="event" id="id_event" class="form-select">
                <option value="" hidden selected>---------</option>
                {% for x in events %}
                {% if not seller.user in x.event_team.all %}
                <option value="{{ x.id }}">{{ x.event_name }} [Organizer: {{ x.organizer.user.full_name }}]</option>
                {% endif %}
                {% endfor %}
            </select>
        </div>

        <div class="form-field mb-3">
            {{ form.contract.label_tag }}
            {% render_field form.contract class+="form-control" %}
        </div>
        <div class="form-field mb-3">
            {{ form.comment.label_tag }}
            <span class="hint text-muted">{{ form.comment.help_text }}</span>
            {% render_field form.comment class+="form-control" %}
        </div>

        <button type="submit" class="btn btn-primary">Send contract</button>
    </form>
</div>

{% endblock body %}

templates/main/login.html
{% extends 'base.html' %}
{% load widget_tweaks %}

{% block title %} ElTukio | Login {% endblock %}

{% block body %}
<div class="p-body">
    <h5 class="text-center mb-0 mt-2"><a href="{% url 'home' %}">ElTukio</a> | User Login</h5>

    <form action="{% url 'login' %}" class="mb-3 p-5" method="POST" novalidate>
        {% csrf_token %}

        <div class="card rounded-md shadow">
            <div class="card-body p-4">
                <div class="form-field mb-2">
                    {{ form.username.label_tag }}
                    {% render_field form.username class+="form-control" %}
                </div>
                <div class="form-field mb-2">
                    {{ form.password.label_tag }}
                    {% render_field form.password class+="form-control" %}
                </div>
                 <div class="cta d-flex justify-content-center gap-sm mt-3">
                    <button type="submit" class="btn btn-primary">
                        <span class="me-2">Login</span>
                        <i class="fa-solid fa-chevron-right"></i>
                    </button>
                </div>
            </div>
        </div>
    </form>

    <div class="text-center">
        <span>Don't have an account yet?</span>
        <a href="{% url 'register' %}">Create account</a>
    </div>
</div>

{% endblock %}